# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jt/projects/workspace/personal_projects/sniffer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jt/projects/workspace/personal_projects/sniffer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jt/projects/workspace/personal_projects/sniffer/CMakeFiles /Users/jt/projects/workspace/personal_projects/sniffer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jt/projects/workspace/personal_projects/sniffer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/Packet/Packet.o: src/Packet/Packet.cpp.o
.PHONY : src/Packet/Packet.o

# target to build an object file
src/Packet/Packet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Packet/Packet.cpp.o
.PHONY : src/Packet/Packet.cpp.o

src/Packet/Packet.i: src/Packet/Packet.cpp.i
.PHONY : src/Packet/Packet.i

# target to preprocess a source file
src/Packet/Packet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Packet/Packet.cpp.i
.PHONY : src/Packet/Packet.cpp.i

src/Packet/Packet.s: src/Packet/Packet.cpp.s
.PHONY : src/Packet/Packet.s

# target to generate assembly for a file
src/Packet/Packet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Packet/Packet.cpp.s
.PHONY : src/Packet/Packet.cpp.s

src/capture/Online.o: src/capture/Online.cpp.o
.PHONY : src/capture/Online.o

# target to build an object file
src/capture/Online.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/capture/Online.cpp.o
.PHONY : src/capture/Online.cpp.o

src/capture/Online.i: src/capture/Online.cpp.i
.PHONY : src/capture/Online.i

# target to preprocess a source file
src/capture/Online.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/capture/Online.cpp.i
.PHONY : src/capture/Online.cpp.i

src/capture/Online.s: src/capture/Online.cpp.s
.PHONY : src/capture/Online.s

# target to generate assembly for a file
src/capture/Online.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/capture/Online.cpp.s
.PHONY : src/capture/Online.cpp.s

src/capture/PacketCapture.o: src/capture/PacketCapture.cpp.o
.PHONY : src/capture/PacketCapture.o

# target to build an object file
src/capture/PacketCapture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/capture/PacketCapture.cpp.o
.PHONY : src/capture/PacketCapture.cpp.o

src/capture/PacketCapture.i: src/capture/PacketCapture.cpp.i
.PHONY : src/capture/PacketCapture.i

# target to preprocess a source file
src/capture/PacketCapture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/capture/PacketCapture.cpp.i
.PHONY : src/capture/PacketCapture.cpp.i

src/capture/PacketCapture.s: src/capture/PacketCapture.cpp.s
.PHONY : src/capture/PacketCapture.s

# target to generate assembly for a file
src/capture/PacketCapture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/capture/PacketCapture.cpp.s
.PHONY : src/capture/PacketCapture.cpp.s

src/parsing/LinkLayer.o: src/parsing/LinkLayer.cpp.o
.PHONY : src/parsing/LinkLayer.o

# target to build an object file
src/parsing/LinkLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/parsing/LinkLayer.cpp.o
.PHONY : src/parsing/LinkLayer.cpp.o

src/parsing/LinkLayer.i: src/parsing/LinkLayer.cpp.i
.PHONY : src/parsing/LinkLayer.i

# target to preprocess a source file
src/parsing/LinkLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/parsing/LinkLayer.cpp.i
.PHONY : src/parsing/LinkLayer.cpp.i

src/parsing/LinkLayer.s: src/parsing/LinkLayer.cpp.s
.PHONY : src/parsing/LinkLayer.s

# target to generate assembly for a file
src/parsing/LinkLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/parsing/LinkLayer.cpp.s
.PHONY : src/parsing/LinkLayer.cpp.s

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tests"
	@echo "... src/Packet/Packet.o"
	@echo "... src/Packet/Packet.i"
	@echo "... src/Packet/Packet.s"
	@echo "... src/capture/Online.o"
	@echo "... src/capture/Online.i"
	@echo "... src/capture/Online.s"
	@echo "... src/capture/PacketCapture.o"
	@echo "... src/capture/PacketCapture.i"
	@echo "... src/capture/PacketCapture.s"
	@echo "... src/parsing/LinkLayer.o"
	@echo "... src/parsing/LinkLayer.i"
	@echo "... src/parsing/LinkLayer.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

